package main

import (
	"bytes"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/steipete/gogcli/internal/safetyprofile"
)

const usage = `Usage: bake-safety-profile <profile.yaml> <output.go>` + "\n"

func main() {
	args := os.Args[1:]
	if len(args) != 2 {
		_, _ = fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}

	raw, err := os.ReadFile(args[0]) // #nosec G304 G703 -- build helper intentionally reads the requested profile path.
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "read profile: %v\n", err)
		os.Exit(1)
	}

	profile, err := safetyprofile.Parse(string(raw))
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "parse profile: %v\n", err)
		os.Exit(1)
	}

	out := generate(profile)
	if err := os.WriteFile(args[1], out, 0o600); err != nil { // #nosec G306 G703 -- build helper intentionally writes the requested generated Go path.
		_, _ = fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}

// generate emits a Go file that resolves the bakedSafety* package-level
// functions for safety_profile builds. Allow and deny rules are encoded as
// FNV-64a hashes in switch statements so that the rule set itself is no
// longer a contiguous, patchable string in the binary.
func generate(profile *safetyprofile.Profile) []byte {
	var out bytes.Buffer
	hasAllowRules := profile.AllowAll || len(profile.AllowRules) > 0

	out.WriteString("// Code generated by cmd/bake-safety-profile; DO NOT EDIT.\n")
	commentName := strings.ReplaceAll(strings.ReplaceAll(profile.Name, "\n", " "), "\r", " ")
	fmt.Fprintf(&out, "// Profile: %s (%d allow, %d deny, allow-all=%t)\n", commentName, len(profile.AllowRules), len(profile.DenyRules), profile.AllowAll)
	out.WriteString("// Hash: FNV-64a over dotted command paths.\n")
	out.WriteString("//go:build safety_profile\n\n")
	out.WriteString("package cmd\n\n")

	out.WriteString("const bakedSafetyProfileNameConst = ")
	out.WriteString(strconv.Quote(profile.Name))
	out.WriteString("\n\n")

	out.WriteString("func bakedSafetyEnabled() bool       { return true }\n")
	out.WriteString("func bakedSafetyProfileName() string { return bakedSafetyProfileNameConst }\n")
	fmt.Fprintf(&out, "func bakedSafetyHasAllowRules() bool { return %t }\n\n", hasAllowRules)

	writeMatcher(&out, "bakedSafetyAllowMatch", profile.AllowRules, profile.AllowAll)
	out.WriteString("\n")
	writeMatcher(&out, "bakedSafetyDenyMatch", profile.DenyRules, false)

	return out.Bytes()
}

func writeMatcher(out *bytes.Buffer, name string, rules []string, matchAll bool) {
	fmt.Fprintf(out, "func %s(path []string) bool {\n", name)
	if matchAll {
		out.WriteString("\treturn true\n}\n")
		return
	}
	if len(rules) == 0 {
		out.WriteString("\treturn false\n}\n")
		return
	}

	out.WriteString("\tif len(path) == 0 {\n\t\treturn false\n\t}\n")
	out.WriteString("\tfor i := 1; i <= len(path); i++ {\n")
	out.WriteString("\t\tswitch bakedSafetyHashPath(path[:i]) {\n")
	out.WriteString("\t\tcase ")

	cases := make([]string, 0, len(rules))
	seen := make(map[uint64]string, len(rules))
	for _, rule := range rules {
		h := safetyprofile.HashRule(rule)
		if existing, dup := seen[h]; dup {
			fmt.Fprintf(os.Stderr, "bake-safety-profile: hash collision between %q and %q (FNV-64a=%#x); pick a different name or extend the hash\n", existing, rule, h)
			os.Exit(1)
		}
		seen[h] = rule
		cases = append(cases, fmt.Sprintf("0x%016x", h))
	}

	const perLine = 4
	for i, c := range cases {
		out.WriteString(c)
		if i == len(cases)-1 {
			break
		}
		out.WriteString(",")
		if (i+1)%perLine == 0 {
			out.WriteString("\n\t\t\t")
		} else {
			out.WriteString(" ")
		}
	}
	out.WriteString(":\n\t\t\treturn true\n")
	out.WriteString("\t\t}\n\t}\n")
	out.WriteString("\treturn false\n}\n")
}
