package main

import (
	"bytes"
	"fmt"
	"os"
	"strconv"

	"github.com/steipete/gogcli/internal/cmd"
)

func main() {
	if len(os.Args) != 3 {
		_, _ = fmt.Fprintln(os.Stderr, "usage: bake-safety-profile <profile.yaml> <output.go>")
		os.Exit(2)
	}

	raw, err := os.ReadFile(os.Args[1]) // #nosec G304 G703 -- build helper intentionally reads the requested profile path.
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "read profile: %v\n", err)
		os.Exit(1)
	}
	if err := cmd.ValidateSafetyProfile(string(raw)); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "parse profile: %v\n", err)
		os.Exit(1)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/bake-safety-profile; DO NOT EDIT.\n")
	out.WriteString("//go:build safety_profile\n\n")
	out.WriteString("package cmd\n\n")
	out.WriteString("var bakedSafetyProfileYAML = ")
	out.WriteString(strconv.Quote(string(raw)))
	out.WriteString("\n")

	if err := os.WriteFile(os.Args[2], out.Bytes(), 0o600); err != nil { // #nosec G306 G703 -- build helper intentionally writes the requested generated Go path.
		_, _ = fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}
